package com.example.puzzlehub.db;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * ScoreEntity - Represents a single game score in the Room database.
 *
 * WHAT IS AN ENTITY?
 * An Entity is a class that defines a table in the database.
 * Each field becomes a column in the table.
 * The @Entity annotation tells Room to create a table called "scores".
 * The @PrimaryKey with autoGenerate=true gives each score a unique ID automatically.
 *
 * Fields:
 * - id: Auto-generated unique identifier
 * - gameType: "MEMORY" or "SLIDE"
 * - difficulty: "EASY", "HARD", "3x3", or "4x4"
 * - moves: Number of moves the player made
 * - timeSeconds: How long the game took in seconds
 * - dateMillis: When the score was saved (timestamp in milliseconds)
 */
@Entity(tableName = "scores")
public class ScoreEntity {
    @PrimaryKey(autoGenerate = true)
    public int id;

    public String gameType;     // "MEMORY" or "SLIDE"
    public String difficulty;   // "EASY", "HARD", "3x3", or "4x4"
    public int moves;           // Number of moves
    public int timeSeconds;     // Time taken in seconds
    public long dateMillis;     // Timestamp when score was saved

    /** Constructor to create a new score (id is auto-generated by Room) */
    public ScoreEntity(String gameType, String difficulty, int moves, int timeSeconds, long dateMillis) {
        this.gameType = gameType;
        this.difficulty = difficulty;
        this.moves = moves;
        this.timeSeconds = timeSeconds;
        this.dateMillis = dateMillis;
    }
}
